"""
B2C lead intake: accept consumer leads from a vendor webhook / API or a CSV
list import, capture consent, dedupe by phone, score under a campaign's offer,
and insert into the shared leads table (market_type = 'b2c').

Unlike B2B (pulled from Google Maps), B2C leads arrive already generated by an
upstream source (lead vendor or ad funnel) and MUST carry consent to be dialed
compliantly. Every intake records lead_source + consent_status + consent_at.

Intake can attach each lead to a CAMPAIGN (client engagement) via campaign_id, so
B2C leads get the same client ownership + history as B2B pulls, and are scored
under that campaign's offer. Without a campaign they fall back to the default offer.
"""

import csv
import io
import re
from datetime import date

import db
import dnc
import scoring
from dialer_import import normalize_phone, format_phone


def _norm(s):
    """Normalize a header/alias to lowercase with single underscores, so
    'Full Name', 'full_name' and 'full-name' all match."""
    return re.sub(r"[^a-z0-9]+", "_", str(s or "").strip().lower()).strip("_")

# Accept a variety of field names vendors/CSVs use -> our columns.
FIELD_ALIASES = {
    "name": ["name", "full_name", "fullname", "consumer_name", "lead_name"],
    "first_name": ["first_name", "firstname", "fname"],
    "last_name": ["last_name", "lastname", "lname"],
    "phone": ["phone", "phone_number", "mobile", "cell", "telephone", "phone1"],
    "email": ["email", "email_address", "e-mail"],
    "city": ["city", "town"],
    "state": ["state", "province", "region"],
    "postcode": ["zip", "zipcode", "postal_code", "postcode", "zip_code"],
    "product_interest": ["product_interest", "interest", "product", "service",
                         "vertical", "campaign_interest"],
    "preferred_contact_time": ["preferred_contact_time", "best_time",
                               "contact_time", "call_time"],
    "consent_status": ["consent_status", "consent", "opt_in", "optin", "tcpa_consent"],
    "consent_at": ["consent_at", "consent_date", "opt_in_time", "timestamp",
                   "trustedform", "consent_timestamp"],
    "source": ["source", "lead_source", "vendor", "publisher", "utm_source"],
    "notes": ["notes", "comments", "note"],
}


def _pick(row_norm, field):
    for alias in FIELD_ALIASES.get(field, []):
        key = _norm(alias)
        if key in row_norm and str(row_norm[key]).strip():
            return str(row_norm[key]).strip()
    return ""


def _normalize_consent(value):
    """Map assorted truthy/opt-in values to a stored consent_status."""
    v = str(value).strip().lower()
    if v in ("1", "true", "yes", "y", "opted_in", "opt_in", "opt-in", "consented", "express"):
        return "opted_in"
    if v in ("0", "false", "no", "n", ""):
        return "unknown"
    return v  # keep any explicit label the source sent


def _default_offer(conn):
    """The offer used to score intake (B2C) leads when none is passed in."""
    return db.get_offer(conn, db.default_offer_slug(conn))


def _resolve_offer(conn, campaign_id=None, offer=None):
    """Pick the offer to score an intake lead under: the campaign's offer when a
    campaign is given, else the passed-in offer, else the default offer."""
    if campaign_id:
        camp = conn.execute(
            "SELECT * FROM campaigns WHERE id = ?", (campaign_id,)).fetchone()
        if camp is not None:
            return db.offer_for_campaign(conn, camp)
    return offer or _default_offer(conn)


def intake_one(conn, data, source, campaign_id=None, offer=None):
    """Insert a single B2C lead from a dict of already-mapped fields, optionally
    attached to a campaign (client engagement). Returns 'added'|'duplicate'|'invalid'.
    `offer` may be pre-resolved (bulk imports) to avoid a per-row lookup."""
    name = (data.get("name") or
            " ".join(p for p in (data.get("first_name"), data.get("last_name")) if p)).strip()
    phone10 = normalize_phone(data.get("phone"))
    if not phone10 or not name:
        return "invalid"
    phone = format_phone(phone10)

    if offer is None:
        offer = _resolve_offer(conn, campaign_id=campaign_id)
    rules = scoring.load_rules(offer)
    lead = {
        "market_type": "b2c",
        "website": "", "email": data.get("email", ""),
        "reviews": None, "rating": None, "unclaimed": None,
        "city": data.get("city", ""), "state": data.get("state", ""),
    }
    score, hook = scoring.evaluate(lead, rules)
    # A lead already on the suppression list arrives pre-blocked.
    status = "dnc" if dnc.is_suppressed(conn, phone) else "new"

    cur = conn.execute(
        "INSERT OR IGNORE INTO leads (phone, business_name, email, city, state, postcode, "
        "category, product_interest, preferred_contact_time, market_type, lead_source, "
        "consent_status, consent_at, score, call_hook, pulled_date, notes, status, campaign_id) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'b2c', ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            phone, name, data.get("email", ""), data.get("city", ""),
            data.get("state", ""), data.get("postcode", ""),
            data.get("product_interest", ""), data.get("product_interest", ""),
            data.get("preferred_contact_time", ""),
            source,
            _normalize_consent(data.get("consent_status", "")),
            data.get("consent_at", "") or db.now_iso(),
            score, hook, str(date.today()), data.get("notes", ""), status, campaign_id,
        ),
    )
    return "added" if cur.rowcount else "duplicate"


def import_csv(conn, text, source, campaign_id=None):
    """Import a CSV of consumer leads, optionally into a campaign. Returns a summary."""
    reader = csv.DictReader(io.StringIO(text))
    if not reader.fieldnames:
        raise ValueError("Empty CSV or no header row.")
    # Resolve the offer once for the whole file (all rows share the campaign).
    offer = _resolve_offer(conn, campaign_id=campaign_id)
    summary = {"added": 0, "duplicates": 0, "invalid": 0, "total": 0}
    for row in reader:
        summary["total"] += 1
        row_norm = {_norm(k): v for k, v in row.items()}
        data = {field: _pick(row_norm, field) for field in FIELD_ALIASES}
        result = intake_one(conn, data, source, campaign_id=campaign_id, offer=offer)
        summary["added" if result == "added" else
                "duplicates" if result == "duplicate" else "invalid"] += 1
    conn.commit()
    return summary
